apps/annuaire/urls.py
from django.conf.urls import url
from annuaire import views

app_name = 'annuaire'
urlpatterns = [
    url(r'^$', views.AnnuaireView.as_view(), name='index'),
    url(r'^profile/me/$',
        views.CurrentProfileDetailView.as_view(), name="current_profile"),
    url(r'^promo/$',
        views.PromoListView.as_view(), name="all_promos"),
    url(r'^promo/(?P<year>\d+)/$',
        views.ProfilePromotionListView.as_view(), name="promo_list"),
    url(r'^profile/(?P<pk>\d+)/$',
        views.ProfileDetailView.as_view(), name="user_profile"),

    url(r'^profile/(?P<pk>\d+)/cotisations$',
        views.ProfileMembershipView.as_view(), name="profile_memberships"),
    url(r'^profile/me/cotisations$',
        views.CurrentProfileMembershipView.as_view(), name="current_profile_memberships"),

    url(r'^search/$',
        views.ProfileSearchView.as_view(), name="search_profile"),

    url(r'^association/membres-honoraires$',
        views.HonoraryProfileListView.as_view(), name="membres-honoraires"),
]

project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from users.views import RegistrationWizard, MembershipDetailView, index, ProfileAutocomplete, process_payment_view


renew_view = login_required(RegistrationWizard.as_view(condition_dict={
    "login": False
}))

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^annuaire/', include('annuaire.urls')),

    # url(r'^register-new/$', RegistrationView.as_view(), name='register_new'),
    url(r'^register/$', RegistrationWizard.as_view(), name='register'),
    url(r'^register/renew/$', renew_view, name='register_renew'),
    url(
        r'^cotisations/(?P<slug>[0-9a-z-]+)/$',
        MembershipDetailView.as_view(),
        name='membership-detail'),
    url(r'^process-payment$', process_payment_view, name='process-payment'),

    # Autocomplete API
    url(r'^profile-autocomplete/$',
        ProfileAutocomplete.as_view(),
        name='profile-autocomplete'),

    url(r'^$', index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/annuaire/models.py
from django.db import models

apps/users/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import \
    AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.utils.text import slugify

from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator
from post_office import mail

from django_fsm import FSMField, transition

import uuid
from datetime import date
from dateutil.relativedelta import relativedelta


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password=password)
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class Profile(models.Model):
    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    # Demographics and public profile
    # -------------------------------

    first_name = models.CharField('Prénom', max_length=50)
    last_name = models.CharField('Nom', max_length=100)

    GENDER_CHOICES = (
        ('f', 'Madame'),
        ('m', 'Monsieur'),
        ('na', 'Autre'))
    gender = models.CharField(
        "Genre", choices=GENDER_CHOICES, max_length=10,
        blank=True, null=True)

    common_name = models.CharField(
        "Nom d'usage (si différent)", max_length=100, blank=True, null=True)

    phone_number = PhoneNumberField(
        "Numéro de téléphone", blank=True, null=True)

    birth_date = models.DateField(
        "Date de naissance", blank=True, null=True)

    birth_place = models.CharField(
        "Lieu de naissance", max_length=100, blank=True, null=True)

    death_info = models.CharField(
        "Informations de décès", max_length=200, blank=True, null=True)

    website = models.URLField(
        "Site web", blank=True, null=True)

    phone_number_isvisible = models.NullBooleanField(
        "Numéro de téléphone visible", default=True)
    website_isvisible = models.NullBooleanField(
        "Site web visible", default=True)
    email_isvisible = models.NullBooleanField(
        "Email visible", default=True)

    # Related to the ENS
    # ------------------

    entrance_year = models.IntegerField(
        "Année d'entrée à l'ENS", null=True, blank=False)

    STATUS_SCHOOL_CHOICES = (
        ('inspecteur', 'Élève inspecteur'),
        ('normalien', 'Élève normalien'),
        ('etudiant', 'Étudiant normalien (anciennement auditeur)'),
    )
    status_school = models.CharField(
        "Statut à l'école", max_length=30,
        choices=STATUS_SCHOOL_CHOICES, null=True, blank=False)

    ENTRANCE_SCHOOL_CHOICES = (
        ('ens_lyon', 'ENS de Lyon'),
        ('ens_lsh', 'ENS Lettres et Sciences humaines'),
        ('fontenay', 'ENS de Fontenay-aux-Roses'),
        ('st_cloud', 'ENS de Saint-Cloud'),
        ('fontenay__st_cloud', 'ENS de Fontenay-Saint-Cloud')
    )
    entrance_school = models.CharField(
        "École d'entrée", max_length=30,
        choices=ENTRANCE_SCHOOL_CHOICES, null=True, blank=False)


    ENTRANCE_FIELD_CHOICES = [
        'Allemand',
        'Anglais',
        'Anthropologie',
        'Arabe',
        'Biologie',
        'Chimie',
        'Chinois',
        'Cinéma',
        'Économie',
        'Espagnol',
        'Géographie',
        'Géologie',
        'Histoire de l’art',
        'Histoire',
        'Informatique',
        'Information / Communication',
        'Italien',
        'Lettres classiques',
        'Lettres modernes',
        'Mathématiques',
        'Musique',
        'Philosophie',
        'Physique',
        'Russe',
        'Sciences cognitives',
        'Sciences de l’éducation',
        'Sciences politiques',
        'Sociologie',
        'Théâtre',
    ]
    ENTRANCE_FIELD_CHOICES = [
        (slugify(c), c) for c in ENTRANCE_FIELD_CHOICES]

    entrance_field = models.CharField(
        "Discipline d'entrée", max_length=200,
        choices=ENTRANCE_FIELD_CHOICES, null=True, blank=False)

    PROFESSIONAL_STATUS_CHOICES = (
        ('active', 'Actif'),
        ('retired', 'Retraité'),
        ('student', 'Étudiant'),
        ('inactive', 'Demandeur d\'emploi')
    )
    professional_status = models.CharField(
        "Situation actuelle", max_length=30,
        choices=PROFESSIONAL_STATUS_CHOICES)

    proof_school = models.FileField(
        "Justificatif de passage à l'ENS", upload_to='uploads/%Y/%m/%d/',
        blank=True, null=True)

    # Utilities
    # ---------

    transfer_data = models.NullBooleanField(
        "Transfert des données avec l'ENS de Lyon")

    is_honorary = models.BooleanField("Membre honoraire", default=False)

    do_not_contact = models.BooleanField("Ne pas contacter", default=False)


    BOOL_CHOICES = ((True, 'Oui'), (False, 'Non'))

    annuaire_papier = models.BooleanField(
        "Recevoir l'annuaire en papier", default=False, choices=BOOL_CHOICES)
    bulletin_papier = models.BooleanField(
        "Recevoir le bulletin en papier", default=False, choices=BOOL_CHOICES)

    def __str__(self):
        if self.common_name:
            return "{} {}".format(self.first_name, self.common_name)

        return "{} {}".format(self.first_name, self.last_name)

    def type_field(self):
        undef = ['Auditeurs', 'Donateur / Etudiant', 'Etudiant', 'Inspecteur',
                 'Second concours']

        science_fields = [
            'Biologie',  'Biologie, chimie, physique, sciences de la Terre',
            'Chimie', 'Geologie', 'Informatique', 'Mathématiques',
            'Mathématiques, physique', 'Mathématiques-informatique',
            'Physique', 'Physique, chimie', 'Sciences',
            'Sciences de la Vie / de la Terre']

        litt_fields = [
            'Arts', 'Etudiant LSH', 'Langues vivantes',
            'Langues vivantes - Allemand', 'Langues vivantes - Anglais',
            'Langues vivantes - Espagnol', 'Langues vivantes - Italien',
            'Langues vivantes - Russe', 'Langues vivantes-Allemand',
            'Langues vivantes-Anglais', 'Langues vivantes-Espagnol',
            'Langues vivantes-Italien', 'Lettres',
            'Lettres - Lettre classiques', 'Lettres - Lettre modernes',
            'Lettres classiques', 'Lettres et arts', 'Lettres modernes',
            'Sciences economiques et sociales', 'Sciences humaines',
            'Sciences humaines - Histoire & géographie',
            'Sciences humaines - Philosophie',
            'Sciences humaines-géographie', 'Sciences humaines-histoire',
            'Sciences humaines-philosophie',
            'Sciences économiques et sociales', 'lettres', 'lettres et arts',
            'sciences sociales']

        if self.entrance_field in science_fields:
            return 'S'
        elif self.entrance_field in litt_fields:
            return 'L'
        else:
            return ''

    def nomenclature(self):
        if self.entrance_school in ['ens_lyon', 'ens_de_lyon']:
            school = 'LY'
        elif self.entrance_school == 'fontenay':
            school = 'FT'
        elif self.entrance_school == 'st_cloud':
            school = 'SC'
        elif self.entrance_school == 'ens_lsh':
            school = 'SH'
        else:
            school = ''

        field = self.type_field()

        if self.entrance_year:
            promo = str(self.entrance_year)
            return "{} {} {}".format(field, school, promo)

    def expiration_membership(self):
        last = self.membership.first()
        if last is None:
            raise ValueError("No membership was found for user {}".format(self))

        return last.start_date + relativedelta(years=last.duration)

    def active_membership(self):
        last = self.membership.first()
        if last is None:
            return False

        expire = last.start_date + relativedelta(years=last.duration)
        return expire > date.today()


class Address(models.Model):
    class Meta:
        verbose_name = "Adresse"
        verbose_name_plural = "Adresses"

    TYPE_CHOICES = (
        ('private_postal', 'Personnelle (privée)'),
        ('public_postal', 'Personnelle (publique)'),
        ('public_non_postal', 'Professionnelle (publique)'),
        ('private_forward', 'Adresse de contact (privée)')
    )

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    type = models.CharField(
        "Type", choices=TYPE_CHOICES, max_length=30, default='private_postal')
    line_1 = models.CharField("Ligne 1", max_length=200)
    line_2 = models.CharField("Ligne 2", max_length=200, blank=True)
    postal_code = models.CharField("Code postal", max_length=30)
    city = models.CharField("Commune", max_length=50, blank=False)
    state_province = models.CharField(
        "State/Province", max_length=40, blank=True)
    country = models.CharField("Pays", max_length=40, blank=False)

    def is_public(self):
        return self.type in ['public_postal', 'public_non_postal']


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'Utilisateur'
        verbose_name_plural = 'Utilisateurs'
        db_table = 'auth_user'

    USERNAME_FIELD = 'email'
    objects = UserManager()

    # Generic fields
    email = models.EmailField('Email', max_length=255, unique=True)

    # Generic flags
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    profile = models.OneToOneField(
        Profile, null=True, verbose_name="Profil", related_name='user',
        on_delete=models.CASCADE)

    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return self.is_admin

apps/annuaire/views.py
from django.views.generic import TemplateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models.aggregates import Count

import django_filters
import django_tables2 as tables

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field

from users.models import Profile
from . import filters


@method_decorator(login_required, name='dispatch')
class AnnuaireView(TemplateView):
    template_name = "annuaire/index.html"


@method_decorator(login_required, name='dispatch')
class PromoListView(TemplateView):
    template_name = "annuaire/promo_list.html"

    def get_context_data(self, **kwargs):
        query = Profile.objects.values('entrance_year').order_by('entrance_year').annotate(Count('entrance_year'))
        counts = {
            c['entrance_year']: c['entrance_year__count']
            for c in query if c['entrance_year'] is not None
        }

        context = super(PromoListView, self).get_context_data(**kwargs)
        context['counts_promo'] = sorted(counts.items(), reverse=True)
        return context


@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView):
    template_name = "annuaire/profile_detail.html"
    queryset = Profile.objects.all()

    def is_current_user(self):
        return self.get_object() == self.request.user.profile


@method_decorator(login_required, name='dispatch')
class CurrentProfileDetailView(ProfileDetailView):
    def get_object(self):
        return self.request.user.profile


@method_decorator(login_required, name='dispatch')
class ProfileMembershipView(DetailView):
    template_name = "annuaire/profile_membership_detail.html"
    queryset = Profile.objects.all()

    def is_current_user(self):
        return self.get_object() == self.request.user.profile


@method_decorator(login_required, name='dispatch')
class CurrentProfileMembershipView(ProfileMembershipView):
    def get_object(self):
        return self.request.user.profile

# Table views & utils
# -------------------

class ProfileTable(tables.Table):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'entrance_school',
                  'entrance_year', 'entrance_field')

    first_name = tables.LinkColumn("annuaire:user_profile", args=[tables.utils.A('pk')], verbose_name="Prénom")
    last_name = tables.LinkColumn("annuaire:user_profile", args=[tables.utils.A('pk')], verbose_name="Nom")
    entrance_school = tables.Column(verbose_name="École")
    entrance_year = tables.Column(verbose_name="Année d'entrée")
    entrance_field = tables.Column(verbose_name="Discipline d'entrée")


class PagedFilteredTableView(tables.SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'

    def get_queryset(self, **kwargs):
        qs = super(PagedFilteredTableView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super(PagedFilteredTableView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


@method_decorator(login_required, name='dispatch')
class ProfileListView(PagedFilteredTableView):
    template_name = "annuaire/profile_list.html"
    paginate_by = 25
    model = Profile

    table_class = ProfileTable
    filter_class = filters.ProfileListFilter
    formhelper_class = filters.ProfileListFormHelper

    def post(self, request, *args, **kwargs):
        return PagedFilteredTableView.as_view()(request)


@method_decorator(login_required, name='dispatch')
class ProfilePromotionListView(ProfileListView):
    def get_queryset(self, **kwargs):
        qs = super(ProfileListView, self).get_queryset(**kwargs)
        qs = qs.filter(entrance_year=self.kwargs['year'])
        return qs


@method_decorator(login_required, name='dispatch')
class ProfileSearchView(ProfileListView):
    template_name = "annuaire/profile_search.html"

    filter_class = filters.SearchFilter
    formhelper_class = filters.SearchFormHelper


@method_decorator(login_required, name='dispatch')
class HonoraryProfileListView(ListView):
    template_name = "annuaire/membres_honoraires.html"
    model = Profile
    queryset = Profile.objects.filter(is_honorary=True).order_by('last_name', 'first_name')

templates/annuaire/index.html
{% extends "base.html" %}


{% block content %}

<div class="row justify-content-center">

<div class="col-md-8">
<h3 class="mb-2">L'annuaire des anciens</h3>

<p>Vous n'arrivez pas à effectuer votre recherche en
ligne ? N'hésitez pas à nous contacter directement en envoyant un email à
l'association : <a href="mailto:ca@lyon-normalesup.org">ca@lyon-normalesup.org</a></p>

<p>Retrouvez aussi directement l'ensemble des membres de votre <a href="https://lyon-normalesup.org/?page_id=679">conseil
d'administration</a> ainsi que les <a href="{% url 'annuaire:membres-honoraires' %}">membres d'honneur</a> de l'association.</p>

<div class="card-deck">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Rechercher un normalien</h4>
      <h6 class="card-subtitle mb-2 text-muted">parmi plus de 14 000 anciens</h6>
      <div class="d-flex justify-content-center my-2">
        <span class="fa-stack fa-4x icon-faded">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-search fa-stack-1x fa-inverse"></i>
        </span>
      </div>
      <p class="card-text">À la recherche d'un ami perdu de vu, d'une connaissance
      rencontrée à l'ENS ou d'anciens étudiants près de chez vous ? Utilisez nos
      fonction de recherche pour parcourir cet annuaire.</p>
    </div>
    <div class="card-footer text-muted">
      <a href="{% url 'annuaire:search_profile' %}" class="card-link">Rechercher dans l'annuaire</a>
    </div>
  </div>
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Normaliens par promo</h4>
      <h6 class="card-subtitle mb-2 text-muted">de 1921 à 2017</h6>
      <div class="d-flex justify-content-center my-2">
        <span class="fa-stack fa-4x icon-faded">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-users fa-stack-1x fa-inverse"></i>
        </span>
      </div>
      <p class="card-text">Explorez l'ensemble des promotions passées dans les ENS
      de St-Cloud, Fontenay-aux-Roses et Lyon. Notre annuaire reprend l'ensemble
      des publications au bulletin officiel ainsi que tous les adhérents de
      l'association.</p>
    </div>
    <div class="card-footer text-muted">
      <a href="{% url 'annuaire:all_promos' %}" class="card-link">Voir les promotions</a>
    </div>
  </div>
</div>

</div>
</div>

{% endblock %}

templates/annuaire/membres_honoraires.html
{% extends "base.html" %}
{% load querystring from django_tables2 %}
{% load title from django_tables2 %}
{% load crispy_forms_tags %}



{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'annuaire:index' %}">Annuaire</a></li>
  <li class="breadcrumb-item">Membres honoraires</li>
</ol>

<div class="row justify-content-center">
<div class="col-md-8">
  <h4 class="my-4">Membres honoraires de l'association</h4>

  <p>Les membres d'honneur sont des personnes physiques ou morales ayant rendu
  des services éminents pour la création, le fonctionnement ou le rayonnement
  des ENS. </p>

  <ul class="list-group">
  {% for p in object_list %}
  <li class="list-group-item">
    <a href="{% url 'annuaire:user_profile' p.id %}">
      {{p}}</a>&nbsp;
      {% if p.nomenclature %}
      <span class="badge badge-primary">{{p.nomenclature}}</span>
      {% endif %}
    </li>
  {% endfor %}
  </ul>

</div>
</div>
{% endblock %}

templates/annuaire/profile_detail.html
{% extends "base.html" %}
{% load admin_urls %}

{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'annuaire:index' %}">Annuaire</a></li>
  {% if object.entrance_year %}
  <li class="breadcrumb-item"><a href="{% url 'annuaire:all_promos' %}">Normaliens par promotion</a></li>
  <li class="breadcrumb-item"><a href="{% url 'annuaire:promo_list' object.entrance_year %}">{{ object.entrance_year}}</a></li>
  <li class="breadcrumb-item active">{{ object }} <span class="badge badge-primary">{{object.nomenclature}}</span></li>
  {% else %}
  <li class="breadcrumb-item active">{{ object }}</li>
  {% endif %}
</ol>

<div class="row justify-content-center">
<div class="col-md-8">
  <h1 class="mb-2">{{ object }}
    {% if object.is_honorary %}
    <small class="text-muted">(membre honoraire)</small>
    {% endif %}
  </h1>

  {% if user.is_admin %}
  <div class="breadcrumb">
    <div class="p-2 d-inline">
      <span>Accès admin</span>
    </div>
    <div class="btn-group m-2" role="group" aria-label="First group">
      {% if object.user %}
      <a class="btn btn-outline-warning" href="{% url 'admin:users_user_change' object.user.id %}">Editer le compte</a>
      {% else %}
      <a class="btn btn-outline-warning disabled" >Pas de compte associé</a>
      {% endif %}
      <a class="btn btn-outline-warning" href="{% url 'admin:users_profile_change' object.id %}">Editer le profil</a>
      <a class="btn btn-outline-danger" href="{% url 'admin:users_profile_delete' object.id %}">Supprimer le profil</a>
    </div>
    <div class="btn-group" role="group" aria-label="Second group">
      {% with last_m=object.membership.first %}
      {% if last_m %}
      <a class="btn btn-outline-primary" href="{% url 'admin:users_membership_change' last_m.id %}">Dernière adhésion en {{last_m.start_date.year}}</a>
      {% else %}
      <a class="btn btn-outline-primary disabled">Aucune adhésion</a>
      {% endif %}
      <a class="btn btn-outline-primary" href="{% url 'admin:users_membership_add' %}">Nouvelle adhésion manuelle</a>
      {% endwith %}
    </div>
  </div>
  {% endif %}

  <div class="list-group">
    {% if object.entrance_year %}
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Entrée en {{object.entrance_year }}, {{object.get_entrance_school_display}}</h5>
      </div>
      <p class="mb-1">sur voie « {{object.entrance_field}} »</p>
    </div>
    {% endif %}

    {% if object.website_isvisible and object.website is not None %}
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Site web personnel</h5>
      </div>
      <p class="mb-1"><a href="{{ object.website }}">{{ object.website }}</a></p>
    </div>
    {% endif %}

    {% if object.email_isvisible and object.user.email > '' %}
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Contacter par email</h5>
      </div>
      <p class="mb-1"><a href="{{ object.user.email }}">{{ object.user.email }}</a></p>
    </div>
    {% endif %}


    {% if object.phone_number_isvisible and object.phonenumber is not None %}
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Site web personnel</h5>
      </div>
      <p class="mb-1"><a href="tel:{{ object.phone_number}}">{{ object.phone_number}}</a></p>
    </div>
    {% endif %}

    {% for add in object.address_set.all %}
    {% if view.is_current_user or add.is_public %}
    <div class="list-group-item list-group-item-action flex-column align-items-start {{ add.is_public | yesno:',list-group-item-warning'}}">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Adresse postale</h5>
      </div>
      <p class="mb-1">{{ add.line_1 }} {{ add.line_2 }}</p>
      <p class="mb-1">{{ add.postal_code }} {{ add.city }}</p>
      <p class="mb-1">{{ add.country }}</p>
    </div>
    {% endif %}
    {% endfor %}
    </div>
</div>
</div>
{% endblock %}

templates/annuaire/profile_membership_detail.html
{% extends "base.html" %}
{% load admin_urls %}

{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'annuaire:index' %}">Annuaire</a></li>
  <li class="breadcrumb-item"><a href="{% url 'annuaire:all_promos' %}">Normaliens par promotion</a></li>
  <li class="breadcrumb-item"><a href="{% url 'annuaire:promo_list' object.entrance_year %}">{{ object.entrance_year}}</a></li>
  <li class="breadcrumb-item active">
    <a href="{% url 'annuaire:user_profile' object.id %}">{{ object }}</a>
    <span class="badge badge-primary">{{object.nomenclature}}</span>
  </li>
  <li class="breadcrumb-item active">Cotisations</li>
</ol>

<div class="row justify-content-center">
<div class="col-md-8">
  <h1 class="my-2">Cotisations de {{ object }}</h1>

  {% if user.is_admin %}
  {% endif %}

  <div class="list-group">
    {% for m in object.membership.all %}
    <a href="{% url 'membership-detail' m.uid %}" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Cotisation {{m.start_date.year}}</span></h5>
        {% if m.status == 'submitted' %}
        <small class="text-warning"><i class="fa fa-clock-o" aria-hidden="true"></i> adhésion en cours</small>
        {% elif m.status == 'accepted' %}
        <small class=""><i class="fa fa-check-circle-o text-success" aria-hidden="true"></i> adhésion valide</small>
        {% else %}
        <small class="text-danger"><i class="fa fa-times" aria-hidden="true"></i> adhésion rejetée</small>
        {% endif %}
      </div>
      {% if m.amount is None %}
      <p class="mb-1">Adhésion gratuite</p>
      <small>Adhésion validée le {{ m.payment_on.date }}</small>
      {% else %}
      <p class="mb-1">Adhésion {{ m.get_membership_type_display }} d'un montant de {{ m.amount }} €</p>
      <small>Paiement par {{m.get_payment_type_display | lower}} reçu le {{ m.payment_on.date }}</small>
      {% endif %}
    </a>
    {% endfor %}
  </div>
</div>
</div>
{% endblock %}

templates/annuaire/promo_list.html
{% extends "base.html" %}


{% block content %}

<div class="row justify-content-center">

<div class="col-md-3">
  <h5 class="my-2">Rechercher un normalien</h5>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente labore recusandae aliquid nobis voluptates deserunt laudantium voluptatibus doloremque sit consequatur numquam quam hic exercitationem, blanditiis! Impedit labore, quas quisquam ducimus.</p>

</div>

<div class="col-md-9">

<h3 class="my-2">Normaliens par promotion</h3>

<div class="d-flex flex-wrap">
{% for promo, count in counts_promo %}
  <div class="card card-outline-primary w-25 my-2 mr-4">
    <div class="card-block">
      <h4 class="card-title">
        <a href="{% url 'annuaire:promo_list' promo %}">Promo {{promo}}</a>
      </h4>
      <h6 class="card-subtitle mb-2 text-muted">{{count}} personnes</h6>
      <!-- <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a> -->
    </div>
  </div>
{% endfor %}
</div>

</div>

</div>

{% endblock %}