annuaire_app/urls.py
from django.conf.urls import url
from annuaire_app import views

app_name = 'annuaire_app'
urlpatterns = [
    url(r'^$', views.AnnuaireView.as_view(), name='index'),
    url(r'^profile/me/',
        views.CurrentProfileDetailView.as_view(), name="current_profile"),
    url(r'^promo/(?P<year>\d+)/$',
        views.ProfilePromotionListView.as_view(), name="promo_list"),
    url(r'^profile/(?P<pk>\d+)/$',
        views.ProfileDetailView.as_view(), name="user_profile"),
]

apps/annuaire/urls.py
from django.conf.urls import url
from annuaire import views

app_name = 'annuaire'
urlpatterns = [
    url(r'^$', views.AnnuaireView.as_view(), name='index'),
    url(r'^profile/me/$',
        views.CurrentProfileDetailView.as_view(), name="current_profile"),
    url(r'^promo/$',
        views.PromoListView.as_view(), name="all_promos"),
    url(r'^promo/(?P<year>\d+)/$',
        views.ProfilePromotionListView.as_view(), name="promo_list"),
    url(r'^profile/(?P<pk>\d+)/$',
        views.ProfileDetailView.as_view(), name="user_profile"),

    url(r'^profile/(?P<pk>\d+)/cotisations$',
        views.ProfileMembershipView.as_view(), name="profile_memberships"),
    url(r'^profile/me/cotisations$',
        views.CurrentProfileMembershipView.as_view(), name="current_profile_memberships"),

    url(r'^search/$',
        views.ProfileSearchView.as_view(), name="search_profile"),

    url(r'^association/membres-honoraires$',
        views.HonoraryProfileListView.as_view(), name="membres-honoraires"),
]

project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from users.views import RegistrationWizard, MembershipDetailView, index, ProfileAutocomplete, process_payment_view


renew_view = login_required(RegistrationWizard.as_view(condition_dict={
    "login": False
}))

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^annuaire/', include('annuaire.urls')),

    # url(r'^register-new/$', RegistrationView.as_view(), name='register_new'),
    url(r'^register/$', RegistrationWizard.as_view(), name='register'),
    url(r'^register/renew/$', renew_view, name='register_renew'),
    url(
        r'^cotisations/(?P<slug>[0-9a-z-]+)/$',
        MembershipDetailView.as_view(),
        name='membership-detail'),
    url(r'^process-payment$', process_payment_view, name='process-payment'),

    # Autocomplete API
    url(r'^profile-autocomplete/$',
        ProfileAutocomplete.as_view(),
        name='profile-autocomplete'),

    url(r'^$', index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static "dist/app.bundle.css" %}">
  <title>Espace adhérent | AE ENS</title>
  {% block head %}{% endblock %}
</head>
<body class="pb-2">
  <nav id="top-header" class="top-header navbar navbar-toggleable-md navbar-light bg-faded mb-4">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-main-nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <a class="navbar-brand c" href="#">
        <img class="header-logo" src="{% static "logo_header.png" %}" alt="">
      </a>

      <div class="collapse navbar-collapse" id="header-main-nav">
        <ul class="nav navbar-nav mr-auto">
          {% if not user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'register' %}">Nouvelle adhésion</a>
          </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'annuaire:index' %}">Accès à l'annuaire</a>
          </li>

          {% if user.is_admin %}
          <li class="nav-item"><a class="nav-link text-danger" href="{% url 'admin:index' %}">Administration</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
          {% if user.profile.active_membership %}
          <li class="nav-item active hidden-md-down mr-2">
            <p class="navbar-text">Adhésion jusqu'en {{ user.profile.expiration_membership.year }}</p>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-primary" href="{% url 'register_renew' %}">Ré-adhérer</a>
          </li>
          {% else %}
          <li class="nav-item active mr-2">
            <p class="navbar-text text-danger">Adhésion expirée</p>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-danger" href="{% url 'register_renew' %}">Ré-adhérer</a>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'annuaire:current_profile' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mon profil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'annuaire:current_profile' %}">Mon profil public</a>
              <a class="dropdown-item" href="{% url 'annuaire:current_profile_memberships' %}">Mes cotisations</a>

              <a class="dropdown-item" href="{% url 'account_change_password' %}">Modifier mon mot de passe</a>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Déconnexion</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item active ml-auto">
            <a class="nav-link" href="{% url 'account_login' %}">Connexion à l'annuaire</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
  {% block content %}{% endblock %}
  </div>
  <script type="text/javascript" src="{% static "dist/index.js" %}"></script>
</body>
</head>